parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: 3306
  database_name: order_management
  database_user: root
  database_password: Marketplace123!
  kernel.secret: ThisIsVerySecret!
  kernel.root_dir: '../'


